### PR TITLE
AUR package for installation

### PR DESCRIPTION
**Pull request by diegosouza**
Hello people,

I've just created an [AUR package](https://aur.archlinux.org/packages/hurl-bin/).

### CODE REVIEW

**Comment by jcamiel** [comment]
Hi Diego, thanks for the package this is really a good idea!

Juste before merging your mr, I don't know very well the AUR and I was wondering:

- how do we proceed if we release a new version of Hurl, do you plan to update the package, do we need to ping you, is there a git repo of it, (like we have for Hurl installation on macOS https://github.com/jcamiel/homebrew-hurl) ?
- can anybody submit a updated version of the package in AUR ? Or only you ? Can me (@jcamiel) or Fabrice (@fabricereix) be 'submitter' ?

These may be "dummy" questions but I've really no knowledge in this area...

(we've modified the GitHub action so you can rebase your mr and the checks should be ok now)

**Comment by fabricereix** [comment]
Hi Diego,
is there a specific reason you use the package name 'hurl-bin' rather then 'hurl'?
if possible, we would prefer simply hurl (consistent with curl)

**Comment by diegosouza** [comment]
Hello @jcamiel 

> how do we proceed if we release a new version of Hurl, do you plan to update the package, do we need to ping you, is there a git repo of it, (like we have for Hurl installation on macOS https://github.com/jcamiel/homebrew-hurl) ?

I'm already subscribed to relases in this repo. So, I'll receive the email from GitHub, to commit the change in the [repo](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hurl-bin#n4).

> can anybody submit a updated version of the package in AUR ? Or only you ? Can me (@jcamiel) or Fabrice (@fabricereix) be 'submitter' ?

That was my first AUR package, so I'm still learning about it. I think I can add you two as co-maintainers, if you have AUR user + ssh keys properly configured there.

> (we've modified the GitHub action so you can rebase your mr and the checks should be ok now)

Ok, so I'm gonna try it in the next few hours :+1:

**Comment by fabricereix** [comment]
ok for hurl-bin, because it is built directly from the binary

in the future, when it is built from source, we can create the 'hurl' package

**Comment by diegosouza** [comment]
Hello @fabricereix 

> is there a specific reason you use the package name 'hurl-bin' rather then 'hurl'?
> if possible, we would prefer simply hurl (consistent with curl)

The [AUR Submission Guidelines](https://wiki.archlinux.org/index.php/AUR_submission_guidelines) says:

`Packages that use prebuilt deliverables, when the sources are available, must use the -bin suffix`

Since the package I created is a wrapper to download, extract and to copy binary + manual files in the correct directories, it must be called `hurl-bin`. The `hurl` package would be another one, more complex, dependencies to run/compile + installation. We can make it later together.

**Pull request merged**
